### ISSUE TITLE
System.out.println is not logged

### ISSUE THREAD

**Issue by milesje** [grgrzybek/tomcat-slf4j-logback#101]
With the tomcat-juli logging a println statement would be logged to the catalina.log file, but this does not happen with this implementation (tomcat-7.0.42).

**Comment by hazendaz** [comment]
Where are is this logging occuring?  Within tomcat or withing your code?  This library only addresses direct tomcat logging.

**Comment by hazendaz** [comment]
No response from user, closing issue.  Tomcat doesn't use System.out.println, our project is for printing within tomcat itself.  User is likely trying to print within their code which isn't going to print to catalina.log.  It would print to console out or whatever setting they have.
