### ISSUE TITLE
Handling of access log valve and its configuration file

### ISSUE THREAD

**Issue by antaflos** [grgrzybek/tomcat-slf4j-logback#115]
It seems when using tomcat-juli-7.0.70-slf4j-1.7.21-logback-1.1.7.zip with Tomcat 7.0.70 the access log valve configuration is either not found or ignored when the specified path to logback-access.xml contains `${catalina.home}`. This is somewhat supported by the documentation, but it only says that `${catalina.home}` is no longer necessary, not that it prevents Tomcat from loading the specified logback-access.xml.

For reference, this is how we usually configure the access log valve for each of our Tomcat instances in server.xml (we use the separation between CATALINA_HOME and CATALINA_BASE to  run multiple instances from one global CATALINA_HOME):

```xml
            <Valve className="ch.qos.logback.access.tomcat.LogbackValve" 
                   filename="${catalina.home}/conf/logback-access.xml"
                   quiet="true"
                   />
```

This works for Tomcat < 7.0.69 and tomcat-slf4j-logback for these versions, but not with Tomcat 7.0.70 as specified above. No access log is written at all when the filename for logback-access.xml is specified like this.

If I remove `${catalina.home}` it works: the configuration file is found/loaded and access logs are written.

The problem is that we use multiple Tomcat and tomcat-slf4j-logback versions throughout our infrastructure, and manage them using Puppet. Previous versions of tomcat-slf4j-logback won't find logback-access.xml unless it is specified absolutely and/or with `${catalina.home}`, but current versions don't find the file unless `${catalina.home}` *is not* specified.

This makes it difficult or at least cumbersome to cater to the needs of different Tomcat/tomcat-slf4j-logback versions.

So I am asking: is it possible to fix up tomcat-slf4j-logback in such a way that the above access log valve definition works with newer versions as well? This way we can keep using `filename="${catalina.home}/conf/logback-access.xml"` throughout our infrastructure and don't have to differentiate between older and newer versions of Tomcat/tomcat-slf4j-logback in this regard.

**Comment by hazendaz** [comment]
Please review the latest build.  Logback recently changed how they handle this and we applied the same.  Basically it's getting dupilcate catalina.home if you define it.  That is because logback internally is adding catalina.home itself.
