### ISSUE TITLE
Move to organization 'tomcat-slf4j-logback'

### ISSUE THREAD

**Issue by hazendaz** [grgrzybek/tomcat-slf4j-logback#127]
@grgrzybek I think we should move this to an organization.  Simply 'tomcat-slf4j-logback' should do it.  I can do majority of work then can invite you over.  At that point you would need to transfer ownership over.  What do you think?

This approach in turn can result in groupId for maven central releases to change to 'com.github.tomcat-slf4j-logback'.  It additionally will give me a bit of extra access so I can do things like properly hook this to travis CI and versioneye rather than off my personal account.  That in turn allows some additional build configurations to occur like most recent commit I added to auto release snapshots to sonatype (tied to root repo).

**Comment by grgrzybek** [comment]
@hazendaz hello

Thank you for all your great effort you put into this project. After I changed my job I:
 - expected to work with much work open source projects (I'm already in camel, aries and karaf)
 - didn't expect **not** to use Tomcat at all ;) (we're using Jetty and Undertow)

I'll transfer the ownership of this project to you and I trust you fully.

cheers
Grzegorz

**Comment by grgrzybek** [comment]
However it gives me: "hazendaz/tomcat-slf4j-logback already exists" when I transfer the ownership to you. I think you have to rename your fork.

**Comment by hazendaz** [comment]
@grgrzybek I just created an organization.  If you can transfer it over to 'tomcat-slf4j-logback/tomcat-slf4j-logback' that will work.  I invited you there as well.  The process will auto update everyones forks.

**Comment by grgrzybek** [comment]
done!

**Comment by hazendaz** [comment]
Sweet!  Thanks.
