### ISSUE TITLE
LOGGING_MANAGER=-Dnop breaks per webapp behavior or JUL

### ISSUE THREAD

**Issue by mpontes** [grgrzybek/tomcat-slf4j-logback#37]
The advised setting of adding ``LOGGING_MANAGER=-Dnop``to setenv.sh, which causes the ``-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager`` parameter to be omitted from Tomcat's command line, will make java.util.logging's fall back to using java.util.logging.LogManager as its manager, which isn't webapp aware. This causes issues when each webapp tries to configure jul by itself (by adding handlers, for example).

I was attempting to use the jul-to-slf4j bridge to make jul logging go through SLF4J and then through Logback, in order to route jul logs that are emitted by libraries that I don't control (things like JAX-WS and Jersey) through Logback as well. Each webapp already configures its own Logback with their own parameters and logging files, which they already normally use through SLF4J, but also initialize the jul-to-slf4j bridge by registering SLF4JBridgeHandler with JUL's LogManager in a startup listener. None of these (logback-classic, sl4fj, jul-to-slf4j) are in the Tomcat classloader, they are being shipped in each webapp's WEB-INF/lib specifically so I can use different logback.xml settings for each webapp.

Since the LogManager isn't ClassLoaderLogManager anymore, and java.util.logging.LogManager is in the system classloader, each jul-to-slf4j initialization overrides the previous webapp's handler. As an end result, every jul log goes through the SLF4JBridgeHandler class that is in the classloader of the last webapp that performed the initialization and therefore uses the Logback instance and configuration of the last application.

Removing ``LOGGING_MANAGER=-Dnop`` makes Tomcat go back to using ClassLoaderLogManager as its jul manager and the jul-to-slf4j handlers don't override eachother. Each webapp then sees the SLF4JBridgeHandler from its own classloader and routes the log through its own instance of Logback properly.

Is there any reason why this setting is being recommended? It seems to me that keeping jul's logging manager set to org.apache.juli.ClassLoaderLogManager is highly beneficial to applications/libraries that use jul logging and it doesn't seem to impact anything else.

**Comment by grgrzybek** [comment]
Hi Miguel
Recently I had not that much time to check this project (I have to find out why I didn't get github notifications about this issue).
I'll check this.

**Comment by grgrzybek** [comment]
Miguel
I've checked your scenario and deployed two webapps with separate `logback.xml` configurations. All applications did was to declare a listener:
```
    @Override
    public void contextInitialized(ServletContextEvent servletContextEvent) {
        SLF4JBridgeHandler.install();
        Logger.getLogger("grgr.test").info("Context initialized: " + servletContextEvent.getServletContext().getContextPath());
    }

    @Override
    public void contextDestroyed(ServletContextEvent servletContextEvent) {
        Logger.getLogger("grgr.test").info("Context destroyed: " + servletContextEvent.getServletContext().getContextPath());
        SLF4JBridgeHandler.uninstall();
    }
```

I removed `LOGGING_MANAGER=-Dnop` entirely (leaving Tomcat's default `ClassloaderLogManager` and everything worked fine. I don't remember why I had to remove it in the first place (I think this `ClassloaderLogManager` wasn't there initially ;)

Thanks for opening this issue - now everything works fine.
