### ISSUE TITLE
How to make use of the SMTPAppender ?

### ISSUE THREAD

**Issue by kbjp** [grgrzybek/tomcat-slf4j-logback#68]
Hi,
Could someone tell me know how I can use the STMPAppender in combination with tomcat-slf4j-logback ? (I'm getting "java.lang.ClassNotFoundException: javax.mail.internet.AddressException").
Ideally, I would also like to use the STMPAppender in my deployed web applications as well.
(the idea being to send an email notification for any caught or uncaught appilcation errors)
Thank you very much in advance for your feedback.
Regards
kbjp
PS: if I simply add the mail jar to the CLASSPATH through setenv.bat, it kind of "works" but seem to be conflicting with the mail jar from my applications.

**Comment by hazendaz** [comment]
Would dropping javax.mail in tomcat lib work for you?


Sent by Outlook for Android





On Mon, Jul 20, 2015 at 5:25 PM -0700, "kbjp" <notifications@github.com> wrote:
Hi,
Could someone tell me know how I can use of the STMPAppender in combination with tomcat-slf4j-logback ? (I'm getting "java.lang.ClassNotFoundException: javax.mail.internet.AddressException").
Ideally, I would also like to use the STMPAppender in my deployed web applications as well.
(the idea being to send an email notification for any caught or uncaught appilcation errors)
Thank you very much in advance for your feedback.
Regards
kbjp

---
Reply to this email directly or view it on GitHub:
https://github.com/grgrzybek/tomcat-slf4j-logback/issues/68

**Comment by kbjp** [comment]
sharing the mail jar between tomcat and the deployed applications works but that requires a special build for each web app which excludes mail.jar from the war file...Ideally, I would like to be able to just drop the full war (including mail.jar) into tomcat and have it work as-is.

**Comment by hazendaz** [comment]
I take it adding this in WAR is causing issue in not allowing it to work properly.  Is it possibly you could create a small demo we can check out to see how best to address this?  I don’t know that you really need to exclude the mail jar at webapp level.  Classloader should only load one anyways. If we bring it into this build which is already pretty large, we would want to shade it to avoid classpath issues.  I’m not exactly sure that is worth the effort.  Keep in mind I personally have mail jar running in my own productionized tomcats in the tomcat lib directory.  Most of the projects I work on are maven based so it’s a simply notation to make it provided scope and assume tomcat will have the jar.

 

@grgrzybek – any thoughts on this?

**Comment by grgrzybek** [comment]
@kbjp entire tomcat-slf4j-logback works by *shadowing* `org.slf4j` and `ch.qos.logback` packages, so what Tomcat core sees is actually different set of packages. And it's working fine without conflicts with slf4j/logback JARs in your WAR.
To make it work *the same* with javax.mail, we'd have to *shadow* javax.mail as well.

If you drop `mail.jar` into `$TOMCAT_HOME/lib`, it'll be visible to all web applications **and** to Tomcat itself.
What happens if you have **the same version** of `mail.jar` in both `$TOMCAT_HOME/lib` and in `WEB-INF/lib` of the WAR?

**Comment by kbjp** [comment]
if I just put mail.jar in the lib folder, I still get a classnotfound exception linked to mail.jar during instantiation/construction of the SMTPAppender linked to tomcat. The only way it works for me is if I make mail.jar part of the classpath inside setenv.bat (using win7 + tomcat8 + java8)

Would it be possible to know if you've successfully managed to use an SMTPappender linked to tomcat itself by just putting mail.jar in the lib folder ?
Regards
kbjp

**Comment by grgrzybek** [comment]
OK, I know - you're getting `ClassNotFoundException`, because `$TOMCAT_HOME/bin/tomcat-juli.jar` is loaded **earlier** than class loader for `$TOMCAT_HOME/lib` is set.
That's why you have to add it to `setenv.bat`. I think that when you do it, having `mail.jar` in `WEB-INF/lib` won't do any harm.

**Comment by kbjp** [comment]
If I put the mail.jar in my application war (don't want to put it in tomcat'slib folder as during development I use another web server: undertow, not tomcat), the stmpappender for tomcat itself seems to stop working.
So, as initially discussed, I end up needing a dev profile and a prod profile (where mail.jar is listed as provided). ..I was still hoping for a solution where mail.jar could be part of the war file at any time.

**Comment by grgrzybek** [comment]
If you want to have `mail.jar` in WAR, there's no way Tomcat would see it.
I don't have good solution for you, I'd use SMTPAppender for logging configuration in WAR and have e-mails being sent when error occurs in web application.
I wonder why Tomcat doesn't use `setenv` provided `mail.jar` - I guess it is related to awfully static nature of `javax.mail` - it's full of static fields and methods.

**Comment by kbjp** [comment]
The whole idea is that if an application uncaught exception bubbles up into tomcat, I still want tomcat to notify me about the problem by sending me an email (which is why I end up needing 2 STMP-appenders: one for caught exceptions at the app level and one for uncaught exceptions at the tomcat level)...
I have something working already; I was just hoping for something simpler...Anyway, thanks a lot for the feedback.

**Comment by grgrzybek** [comment]
I usually like to tackle such issues, but I have too much other work to do now before my holidays ;)
In your case, I'd prefer having single, application-wide uncaught exception resolver - that's quite easy to do if you have Spring-based application

**Comment by kbjp** [comment]
yes...Spring is nice...Unfortunately the legacy app I'm currently dealing with is GWT (google-web-toolkit), and in it I have to cater for uncaught exceptions. :-(
Anyway, thanks a lot once again for taking time to provide feedback.

**Comment by hazendaz** [comment]
Closing issue as it appears the discussion is complete.
